### ISSUE TITLE
作者你的webpack的配置文件在哪？没找到/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by wx-wangxiang** [SimonZhangITer/DataVisualization#1]
没找到你的webpack的配置文件

**Comment by SimonZhangITer** [comment]
@wx-wangxiang 在build文件夹里面

**Comment by wx-wangxiang** [comment]
找到了,谢谢了，我一般都放在根目录下的【尴尬】

**Comment by rshuzz** [comment]
缩略图表的标题字体能不能放大一点，有点不好识别

**Comment by SimonZhangITer** [comment]
@rshuzz 缩略图的本意不是看的  需要点击放大到右侧进行查看或操作

**Comment by rshuzz** [comment]
我调了2个小时，后面居然发现这个图表不支持MSIE11和MS Edge @SimonZhangITer

**Comment by SimonZhangITer** [comment]
@rshuzz 感谢反馈。你用MSIE11和MS Edge这两个浏览器直接打开这个网址试试看？[https://simonzhangiter.github.io/DataVisualization/#/dashboard](https://simonzhangiter.github.io/DataVisualization/#/dashboard)

**Comment by rshuzz** [comment]
@SimonZhangITer  以上url Edge打开正常，MSIE11打开为空白；本地项目 Edge打开有背景图，MSIE11打开为空白

**Comment by SimonZhangITer** [comment]
以上url和本地配置一致。IE11打开空白的话，那可能是兼容性有问题了，等有空我去看看这个问题。
