### ISSUE TITLE
css

### ISSUE THREAD

**Issue by gy95** [SimonZhangITer/DataVisualization#4]
`.item {
    padding: 0px;
    margin: 0px;
    width: 68%;
    height: 100%;
    position: absolute
    transform scale(0.33);
    text-align: center;
    transition:all 0.8s;
    background: rgba(32, 32, 35, 0.5)
}`
这里absolute后面加个分号，transform后面加个冒号，设置了class=‘item’的div就不显示了，为啥

**Comment by SimonZhangITer** [comment]
position: absolute后面少了个分号；？

**Comment by gy95** [comment]
> position: absolute后面少了个分号；？

我的意思是我上面的代码可以正常运行，但是加个分号和冒号之后就不对了

**Comment by gy95** [comment]
`<template lang="html">
  <div class="dashboard1">
    <div class="flex-container column">
      <div class="item one" @click="clickChart('1')" style="transform: translate(-22.4%,-33.5%) scale(0.33)">
        <img src="../../../../static/img/1.jpg">
      </div>
      <div class="item two" @click="clickChart('2')" style="transform: translate(-22.4%,0.5%) scale(0.33)">
        <img src="../../../../static/img/2.jpg">
      </div>
      <div class="item three" @click="clickChart('3')" style="transform: translate(-22.4%,34.5%) scale(0.33)">
        <img src="../../../../static/img/3.jpg">
      </div>
      <div class="item four active" @click="clickChart('4')" style="transform: translate(43.7%, 0) scale(1)">
        <img src="../../../../static/img/4.jpg">
      </div>
    </div>

  </div>
</template>


<script>
export default {
  name: "DashboardAdmin",
  components: {},
  data() {
    return {
      items: [],
    };
  },
  mounted() {
    this.init();
  },
  watch: {
    $route: "isDashBoard"
  },
  methods: {
    _resize() {
      this.$root.charts.forEach((myChart) => {
        myChart.resize()
      })
    },
    init() {
      this.items = document.querySelectorAll('.flex-container .item')
      for (let i = 0; i < this.items.length; i++) {
        this.items[i].dataset.order = i + 1;
      }
    },
    clickChart(clickIndex) {
      let activeItem = document.querySelector('.flex-container .active')
      let activeIndex = activeItem.dataset.order
      let clickItem = this.items[clickIndex - 1]
      if (activeIndex === clickIndex) {
        return
      }
      activeItem.classList.remove('active')
      clickItem.classList.add('active')
      this._setStyle(clickItem, activeItem)
    },
    _setStyle(el1, el2) {
      let transform1 = el1.style.transform
      let transform2 = el2.style.transform
      el1.style.transform = transform2
      el2.style.transform = transform1
    },

  }
};
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
* {
  box-sizing: border-box;
}

.item {
    padding: 0px;
    margin: 0px;
    width: 68%;
    height: 100%;
    position: absolute
    transform scale(0.33);
    text-align: center;
    transition:all 0.8s;
    background: rgba(32, 32, 35, 0.5)
}
    
.dashboard1 {
    position: relative;
    width: 100%;
    height: 100%;
    margin: 0px;
    padding: 0px;
    padding-top: 5%;

    background-size: 100% 100%;
}
    
.flex-container.column {
    position: relative;
    height: 90%;
    width: 90%;
    overflow: hidden;
    margin:  0 auto 100px auto;
    box-sizing: content-box;
}
    
.active {
    height: 100%;
    width: 69%;
    margin-left: 10px;
    line-height: 300px;
}
    
</style>
`
这是我大致的代码

**Comment by gy95** [comment]
<style rel="stylesheet/scss" lang="scss" scoped>
我style头是这样写的

**Comment by SimonZhangITer** [comment]
可以格式化一下代码吗，这样看不太出来问题

**Comment by gy95** [comment]
<template>
  <div class="dashboard1">
    <div class="flex-container column">
      <div class="item one" @click="clickChart('1')" style="transform: translate(-22.4%,-33.5%) scale(0.33)">
        <img src="../../../static/img/1.jpg">
      </div>
      <div class="item two" @click="clickChart('2')" style="transform: translate(-22.4%,0.5%) scale(0.33)">
        <img src="../../../static/img/2.jpg">
      </div>
      <div class="item three" @click="clickChart('3')" style="transform: translate(-22.4%,34.5%) scale(0.33)">
        <img src="../../../static/img/3.jpg">
      </div>
      <div class="item four active" @click="clickChart('4')" style="transform: translate(43.7%, 0) scale(1)">
        <img src="../../../static/img/4.jpg">
      </div>
    </div>
  </div>
</template>


<script>
export default {
  name: "DashboardAdmin",
  components: {},
  data() {
    return {
      items: [],
    };
  },
  mounted() {
    this.init();
  },
  watch: {
    $route: "isDashBoard"
  },
  methods: {
    _resize() {
      this.$root.charts.forEach((myChart) => {
        myChart.resize()
      })
    },
    init() {
      this.items = document.querySelectorAll('.flex-container .item')
      for (let i = 0; i < this.items.length; i++) {
        this.items[i].dataset.order = i + 1;
      }
    },
    clickChart(clickIndex) {
      let activeItem = document.querySelector('.flex-container .active')
      let activeIndex = activeItem.dataset.order
      let clickItem = this.items[clickIndex - 1]
      if (activeIndex === clickIndex) {
        return
      }
      activeItem.classList.remove('active')
      clickItem.classList.add('active')
      this._setStyle(clickItem, activeItem)
    },
    _setStyle(el1, el2) {
      let transform1 = el1.style.transform
      let transform2 = el2.style.transform
      el1.style.transform = transform2
      el2.style.transform = transform1
    },

  }
};
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
* {
  box-sizing: border-box;
}

.item {
    padding: 0px;
    margin: 0px;
    width: 68%;
    height: 100%;
    position: absolute
    transform scale(0.33);
    text-align: center;
    transition:all 0.8s;
    background: rgba(32, 32, 35, 0.5)
}
    
.dashboard1 {
    position: relative;
    width: 100%;
    height: 100%;
    margin: 0px;
    padding: 0px;
    padding-top: 5%;
    background-size: 100% 100%;
}
    
.flex-container.column {
    position: relative;
    height: 90%;
    width: 90%;
    overflow: hidden;
    margin:  0 auto 100px auto;
    box-sizing: content-box;
}
    
.active {
    height: 100%;
    width: 69%;
    margin-left: 10px;
    line-height: 300px;
}
    
</style>

**Comment by gy95** [comment]
[test.zip](https://github.com/SimonZhangITer/DataVisualization/files/2628287/test.zip)

**Comment by SimonZhangITer** [comment]
```
.item {
    padding: 0px;
    margin: 0px;
    width: 68%;
    height: 100%;
    position: absolute;
    transform: scale(0.33);
    text-align: center;
    transition: all 0.8s;
    background: rgba(32, 32, 35, 0.5)
}
```

**Comment by gy95** [comment]
> ```
> .item {
>     padding: 0px;
>     margin: 0px;
>     width: 68%;
>     height: 100%;
>     position: absolute;
>     transform: scale(0.33);
>     text-align: center;
>     transition: all 0.8s;
>     background: rgba(32, 32, 35, 0.5)
> }
> ```

这样的话就出不来了

**Comment by SimonZhangITer** [comment]
你是改了我的代码吗，之前都是可以正常运行的

**Comment by SimonZhangITer** [comment]
你把我的这段样式复制到你的代码试试

**Comment by gy95** [comment]
还是不行  会不会是和我之前的style冲突了

**Comment by gy95** [comment]
解决了，就是和我之前的冲突了 css定位的问题

**Comment by SimonZhangITer** [comment]
好的
